"""Assemble main.tex, a single Springer Nature (sn-jnl) file for Overleaf, and
check it.

Pieces, all in this folder:
    front.tex         title, authors, abstract, keywords
    body.tex          Introduction ... Experimental setup
    results.tex       Results and Discussion; a line %%TABLE:tab_x%% is replaced
                      by the contents of tab_x.tex
    conclusion.tex    Conclusion
    back.tex          back matter after the bibliography (declarations)
The bibliography is regenerated by make_refs.py from the citations in the
assembled text and pasted in, so main.tex needs no .bib file and no \\input.

Checks (structure only; whether a reference is real or a number matches its
source still needs a person): no placeholder left, every \\ref has a label and
every float label is referenced, floats numbered in citation order, no section
with exactly one subsection, every section with subsections opens with prose,
every citation attached with ~, every abbreviation expanded before first use,
no double hyphen or compound hyphen in body text, abstract free of citations,
dashes and parenthetical statistics, figure files present, environments
balanced, no AI attribution, and a report of short adjacent paragraphs.

    python build_main.py            fails on any problem
    python build_main.py --draft    tolerate placeholders and missing tables
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BS = chr(92)
DRAFT = '--draft' in sys.argv


def read(name):
    return open(os.path.join(HERE, name), encoding='utf-8').read()


PREAMBLE = r"""%Version 3.1 December 2024
% See section 11 of the User Manual for version history
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                 %%
%% Please do not use \input{...} to include other tex files.       %%
%% Submit your LaTeX manuscript as one .tex document.              %%
%%                                                                 %%
%% All additional figures and files should be attached             %%
%% separately and not embedded in the \TeX\ document itself.       %%
%%                                                                 %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[pdflatex,sn-mathphys-num]{sn-jnl}% Math and Physical Sciences Numbered Reference Style

%%%% Standard Packages
\usepackage{graphicx}%
\usepackage{multirow}%
\usepackage{amsmath,amssymb,amsfonts}%
\usepackage{amsthm}%
\usepackage[title]{appendix}%
\usepackage{xcolor}%
\usepackage{textcomp}%
\usepackage{manyfoot}%
\usepackage{booktabs}%
\usepackage{algorithm}%
\usepackage{algorithmicx}%
\usepackage{algpseudocode}%
\usepackage{listings}%
\usepackage{array}%
%% ragged right paragraph column for the audit tables
\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
%% mathrsfs is deliberately not loaded: it is unused here, and loading it makes
%% every small math size request the rsfs font.

%% ---------------------------------------------------------------------
%% ADDED FOR COMPILATION ONLY -- delete these six lines once figs/*.png are
%% in place. The three figures are not in this repository; without this the
%% document fails to build on a machine that does not have them. With it,
%% a missing figure renders as a labelled placeholder box and the rest of
%% the document still compiles. Nothing else in the file depends on it.
\newcommand{\figorbox}[2]{\IfFileExists{#2}{\includegraphics[width=#1]{#2}}%
  {\fbox{\parbox[c][45mm][c]{#1}{\centering\ttfamily\small MISSING FIGURE\\#2}}}}
%% ---------------------------------------------------------------------

\theoremstyle{thmstyleone}%
\newtheorem{theorem}{Theorem}%
\newtheorem{proposition}[theorem]{Proposition}%

\theoremstyle{thmstyletwo}%
\newtheorem{example}{Example}%
\newtheorem{remark}{Remark}%

\theoremstyle{thmstylethree}%
\newtheorem{definition}{Definition}%

\raggedbottom

%% The class does \LoadClass[twoside,fleqn]{article}, so odd and even pages get
%% mirrored margins. Passing oneside does not help, because the class applies its
%% own twoside afterwards. Average the two instead.
\AtBeginDocument{%
  \addtolength{\oddsidemargin}{\evensidemargin}%
  \setlength{\oddsidemargin}{0.5\oddsidemargin}%
  \setlength{\evensidemargin}{\oddsidemargin}%
}

%% \bmhead is a level-5 heading while the class sets bookmarksdepth=5, so the
%% back matter jumps four bookmark levels at once and hyperref complains.
\hypersetup{bookmarksdepth=3}

%% DOIs and URLs cannot hyphenate, so the surrounding bibliography lines are set
%% loose. \sloppy permits the loose line but leaves \hbadness at 1000; both are
%% needed, scoped to the bibliography and applied after natbib's own hooks.
\AtBeginDocument{%
  \let\snOrigThebibliography\thebibliography
  \renewcommand{\thebibliography}[1]{%
    \snOrigThebibliography{#1}\sloppy\hbadness=10000\relax}%
}

\begin{document}

"""

# ------------------------------------------------------------- assemble
results = read('results.tex')
for name in re.findall(r'%%TABLE:(\w+)%%', results):
    if os.path.exists(os.path.join(HERE, name + '.tex')):
        table = read(name + '.tex').strip()
    elif DRAFT:
        table = BS + 'RES{table %s not built yet}' % name
    else:
        sys.exit('table file %s.tex missing' % name)
    results = results.replace('%%TABLE:' + name + '%%', table)

parts = [PREAMBLE, read('front.tex').strip(), '\n\n' + BS + 'maketitle\n\n',
         read('body.tex').strip(), '\n\n', results.strip(), '\n\n',
         read('conclusion.tex').strip(), '\n\n' + BS + 'backmatter\n\n%%BIBLIOGRAPHY%%\n\n',
         read('back.tex').strip(), '\n\n' + BS + 'end{document}\n']
if DRAFT:
    parts.insert(1, BS + 'providecommand{' + BS + 'RES}[1]{' + BS + 'textbf{[#1]}}\n\n')
draft = ''.join(parts)
out = os.path.join(HERE, 'main.tex')
open(out, 'w', encoding='utf-8', newline='\n').write(draft)
r = subprocess.run([sys.executable, 'make_refs.py', 'main.tex'], cwd=HERE,
                   capture_output=True, text=True)
print(r.stdout.strip() or r.stderr.strip())
if r.returncode:
    sys.exit('bibliography failed')
# main.tex cites refs.bib through the class's own style (the class sets
# the bibliography style itself); main_selfcontained.tex carries the same list
# as a thebibliography block for a one-file submission.
main = draft.replace('%%BIBLIOGRAPHY%%', read('refs.tex').strip())
open(os.path.join(HERE, 'main_selfcontained.tex'), 'w', encoding='utf-8', newline='\n').write(main)
open(out, 'w', encoding='utf-8', newline='\n').write(
    draft.replace('%%BIBLIOGRAPHY%%', BS + 'bibliography{refs}'))

# --------------------------------------------------------------- checks
problems, notes = [], []
text = re.sub(r'(?m)(?<!' + re.escape(BS) + r')%.*$', '', main)      # drop comments
body_start = text.index(BS + 'section{Introduction}')
body_end = text.index(BS + 'backmatter')
body = text[body_start:body_end]
abstract = re.search(re.escape(BS) + r'abstract\{(.*?)\}\s*' + re.escape(BS) + r'keywords', text, re.S).group(1)

if BS + 'RES{' in text and not DRAFT:
    problems.append('placeholder ' + BS + 'RES left in the text')

# labels and references
labels = re.findall(re.escape(BS) + r'label\{([^}]+)\}', text)
refs = re.findall(re.escape(BS) + r'(?:ref|eqref)\{([^}]+)\}', text)
for k in sorted(set(refs) - set(labels)):
    problems.append('reference to undefined label ' + k)
for k in labels:
    if k.split(':')[0] in ('fig', 'tab', 'eq') and k not in refs:
        problems.append('label never referenced: ' + k)
if len(labels) != len(set(labels)):
    problems.append('duplicate labels: %s' % sorted(k for k in set(labels) if labels.count(k) > 1))

# floats numbered in citation order: the order of \begin{table}/\begin{figure}
# must match the order in which the text first refers to each float
for env in ('table', 'figure'):
    declared = []
    for m in re.finditer(re.escape(BS) + 'begin{' + env + r'}(.*?)' + re.escape(BS) + 'end{' + env + '}', text, re.S):
        lab = re.search(re.escape(BS) + r'label\{([^}]+)\}', m.group(1))
        declared.append((m.start(), lab.group(1) if lab else '?'))
    first_ref = {}
    for m in re.finditer(re.escape(BS) + r'ref\{([^}]+)\}', text):
        first_ref.setdefault(m.group(1), m.start())
    order_decl = [lab for _, lab in declared]
    order_ref = sorted(order_decl, key=lambda lab: first_ref.get(lab, 10 ** 9))
    if order_decl != order_ref:
        problems.append('%ss declared in order %s but first cited in order %s' % (env, order_decl, order_ref))
    for pos, lab in declared:
        if lab in first_ref and first_ref[lab] > pos:
            notes.append('%s %s appears before its first reference' % (env, lab))

# section structure
sections = [(m.start(), m.group(1)) for m in re.finditer(re.escape(BS) + r'section\{([^}]*)\}', body)]
for i, (pos, title) in enumerate(sections):
    end = sections[i + 1][0] if i + 1 < len(sections) else len(body)
    chunk = body[pos:end]
    subs = re.findall(re.escape(BS) + r'subsection\{([^}]*)\}', chunk)
    if len(subs) == 1:
        problems.append('section "%s" has exactly one subsection' % title)
    if subs:
        head = chunk[:chunk.index(BS + 'subsection{')]
        head = re.sub(re.escape(BS) + r'(section|label)\{[^}]*\}', '', head)
        if len(re.findall(r'[A-Za-z]+', head)) < 25:
            problems.append('section "%s" has subsections but no opening paragraph' % title)
    if title == 'Introduction' and subs:
        problems.append('Introduction must not have subheadings')
    if re.search(re.escape(BS) + r'subsubsection\{', chunk):
        notes.append('section "%s" uses subsubsections' % title)
intro = body[:sections[1][0]] if len(sections) > 1 else body
n_items = len(re.findall(re.escape(BS) + r'item\b', intro))
if not 4 <= n_items <= 5:
    problems.append('Introduction contributions list has %d items, not 4 or 5' % n_items)

# citations attached with a non-breaking space
loose = [m.start() for m in re.finditer(r'(?<!~)' + re.escape(BS) + r'cite\{', body)]
if loose:
    ctx = [body[i - 30:i + 20].replace('\n', ' ') for i in loose]
    problems.append('%d citations not attached with ~: %s' % (len(loose), ctx[:4]))

# abstract
if BS + 'cite' in abstract:
    problems.append('abstract contains a citation')
if re.search(r'\(\s*\$?[pdrt]\s*[=<>]', abstract):
    problems.append('abstract contains a parenthetical statistic')
if re.search(r'[A-Za-z]-[A-Za-z]', abstract.replace('S' + BS + '&P', '')):
    problems.append('abstract contains a hyphenated compound')
if '--' in abstract:
    problems.append('abstract contains a dash')
if BS + 'begin{' in abstract or BS + '[' in abstract:
    problems.append('abstract contains a display equation')

# dashes and compound hyphens in body text (math, labels, cites, refs and
# equations excluded); hyphenated proper names that may stay are listed here
ALLOWED = {'KSE-100', 'MA-5', 'MA-20', 'EWMA-10', 'Jolicoeur-Martineau'}
prose = re.sub(r'\$[^$]*\$', ' ', body)
prose = re.sub(re.escape(BS) + r'(cite|label|ref|eqref|includegraphics)(\[[^\]]*\])?\{[^}]*\}', ' ', prose)
prose = re.sub(re.escape(BS) + r'begin\{equation\}.*?' + re.escape(BS) + r'end\{equation\}', ' ', prose, flags=re.S)
prose = prose.replace('S' + BS + '&P', 'SP')
if '--' in prose:
    i = prose.index('--')
    problems.append('double hyphen in body text near: ' + prose[max(0, i - 40):i + 20].replace('\n', ' '))
hy = set(re.findall(r'[A-Za-z0-9]+-[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*', prose)) - ALLOWED
hy = {h for h in hy if not re.fullmatch(r'\d+-\d+', h)}
if hy:
    problems.append('compound hyphens in body text: %s' % sorted(hy))

# abbreviations expanded before first use (all-caps tokens of 2+ letters)
NOABBR = {'GSPC', 'SS', 'DAX', 'NYMEX', 'CSI', 'NVIDIA', 'GTX', 'VIT', 'SENSE', 'KSE', 'TODO',
          'MA', 'EWMA', 'II', 'III', 'M3'}
plain = re.sub(r'\$[^$]*\$', ' ', text[text.index(BS + 'abstract{'):body_end])
plain = re.sub(re.escape(BS) + r'(cite|label|ref|eqref|includegraphics)(\[[^\]]*\])?\{[^}]*\}', ' ', plain)
plain = re.sub(re.escape(BS) + r'[a-zA-Z]+', ' ', plain)
# whole tokens only: CEEMDAN inside ICEEMDAN or LSTM inside BiLSTM must not count
for tok in sorted(set(re.findall(r'(?<![A-Za-z])[A-Z][A-Z0-9]{1,}(?![A-Za-z])', plain))):
    if tok in NOABBR or tok.isdigit():
        continue
    first = re.search(r'(?<![A-Za-z])' + tok + r'(?![A-Za-z])', plain).start()
    if '(' + tok + ')' not in plain[:first + len(tok) + 3]:
        problems.append('abbreviation %s used before it is expanded' % tok)

# figure files, environments, AI attribution, self-containment, tone
for f in re.findall(re.escape(BS) + r'(?:includegraphics(?:\[[^\]]*\])?|figorbox\{[^}]*\})\{([^}]+)\}', text):
    if f.startswith('#'):          # the macro definition itself, not a use
        continue
    if not os.path.exists(os.path.join(HERE, f)) and not DRAFT:
        problems.append('missing figure file ' + f)
for env in set(re.findall(re.escape(BS) + r'begin\{([^}]+)\}', text)):
    nb, ne = text.count(BS + 'begin{' + env + '}'), text.count(BS + 'end{' + env + '}')
    if nb != ne:
        problems.append('environment %s: %d begin, %d end' % (env, nb, ne))
if re.search(r'\b(ChatGPT|GPT-4|language model wrote|generated by AI|AI-generated)\b', main):
    problems.append('AI attribution found in the manuscript')
if BS + 'input{' in text or BS + 'include{' in text or BS + 'bibliographystyle' in text:
    problems.append('main.tex must be self-contained without input/include/bibliographystyle')
if 'we introduce' in body:
    problems.append('"we introduce" used; write "we propose"')

# short adjacent paragraphs (report only)
paras = [p for p in re.split(r'\n\s*\n', prose) if re.search(r'[A-Za-z]', p)
         and not p.strip().startswith(BS)]
for a, b in zip(paras, paras[1:]):
    wa, wb = len(re.findall(r'[A-Za-z]+', a)), len(re.findall(r'[A-Za-z]+', b))
    if wa < 60 and wb < 60 and BS + 'item' not in a + b and BS + 'begin' not in a + b:
        notes.append('two short adjacent paragraphs (%d and %d words): "%s..."' % (wa, wb, a.strip()[:50]))

n_cites = len(set(sum((g.split(',') for g in re.findall(re.escape(BS) + r'cite\{([^}]*)\}', body)), [])))
print('main_selfcontained.tex: %d lines, %d labels, %d references, %d distinct citations, %d words in body'
      % (main.count('\n'), len(labels), len(refs), n_cites, len(re.findall(r'[A-Za-z]+', prose))))
if n_cites < 30:
    problems.append('fewer than 30 references cited (%d)' % n_cites)
for n in notes:
    print('  note: ' + n)
if problems:
    print('PROBLEMS:')
    for p in problems:
        print('  ' + p)
    sys.exit(1)
print('all checks passed')
